<?php

namespace ContainerYcdCx99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZGT7cd8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZGT7cd8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZGT7cd8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reserva' => ['privates', '.errored..service_locator.ZGT7cd8.App\\Entity\\Reserva', NULL, 'Cannot autowire service ".service_locator.ZGT7cd8": it references class "App\\Entity\\Reserva" but no such service exists.'],
        ], [
            'reserva' => 'App\\Entity\\Reserva',
        ]);
    }
}
