<?php

namespace ContainerYcdCx99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CNZ0ar0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CNZ0ar0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CNZ0ar0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'camper' => ['privates', '.errored..service_locator.CNZ0ar0.App\\Entity\\Campers', NULL, 'Cannot autowire service ".service_locator.CNZ0ar0": it references class "App\\Entity\\Campers" but no such service exists.'],
        ], [
            'camper' => 'App\\Entity\\Campers',
        ]);
    }
}
