<?php

namespace ContainerYcdCx99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CL4o199Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cL4o199' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cL4o199'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservaRepository' => ['privates', 'App\\Repository\\ReservaRepository', 'getReservaRepositoryService', true],
        ], [
            'reservaRepository' => 'App\\Repository\\ReservaRepository',
        ]);
    }
}
