<?php

namespace ContainerYcdCx99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CNZ0ar0.App\Entity\Campers' shared service.
     *
     * @return \App\Entity\Campers
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CNZ0ar0": it references class "App\\Entity\\Campers" but no such service exists.');
    }
}
