<?php

namespace ContainerYcdCx99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComentarioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BYQFihD.App\Entity\Comentario' shared service.
     *
     * @return \App\Entity\Comentario
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.BYQFihD": it references class "App\\Entity\\Comentario" but no such service exists.');
    }
}
