<?php

namespace ContainerYcdCx99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRuteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZnMYf8e.App\Entity\Rute' shared service.
     *
     * @return \App\Entity\Rute
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZnMYf8e": it references class "App\\Entity\\Rute" but no such service exists.');
    }
}
