<?php

namespace ContainerYcdCx99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZGT7cd8.App\Entity\Reserva' shared service.
     *
     * @return \App\Entity\Reserva
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZGT7cd8": it references class "App\\Entity\\Reserva" but no such service exists.');
    }
}
