<?php

namespace ContainerKw7VMrb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZnMYf8eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZnMYf8e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZnMYf8e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rute' => ['privates', '.errored..service_locator.ZnMYf8e.App\\Entity\\Rute', NULL, 'Cannot autowire service ".service_locator.ZnMYf8e": it references class "App\\Entity\\Rute" but no such service exists.'],
        ], [
            'rute' => 'App\\Entity\\Rute',
        ]);
    }
}
