<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKw7VMrb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKw7VMrb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKw7VMrb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKw7VMrb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKw7VMrb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kw7VMrb',
    'container.build_id' => 'f7b98b5d',
    'container.build_time' => 1623088804,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKw7VMrb');
